// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGRGxH6P17PN96GCbOyFj1BBKlDqoBfKQ',
    appId: '1:303393597490:web:e6bfa7df42979d3f9a742b',
    messagingSenderId: '303393597490',
    projectId: 'project-d84d9',
    authDomain: 'project-d84d9.firebaseapp.com',
    storageBucket: 'project-d84d9.appspot.com',
    measurementId: 'G-L8R7KEXPHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe09pHaRA7eNCPUxQUcV7VmHMI8at7jAE',
    appId: '1:303393597490:android:577e1e64b50350d89a742b',
    messagingSenderId: '303393597490',
    projectId: 'project-d84d9',
    storageBucket: 'project-d84d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRp2thY17nhw7TjF0rH66Ix9T3bTCZoUY',
    appId: '1:303393597490:ios:b376ca15c7e1dc8f9a742b',
    messagingSenderId: '303393597490',
    projectId: 'project-d84d9',
    storageBucket: 'project-d84d9.appspot.com',
    iosBundleId: 'com.example.latihan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRp2thY17nhw7TjF0rH66Ix9T3bTCZoUY',
    appId: '1:303393597490:ios:2e827dcc9aae0b719a742b',
    messagingSenderId: '303393597490',
    projectId: 'project-d84d9',
    storageBucket: 'project-d84d9.appspot.com',
    iosBundleId: 'com.example.latihan.RunnerTests',
  );
}
