// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyqhtTJ2mqrPlAqEm7b6CYu_Lkki8NOEU',
    appId: '1:57142357984:web:d4a067c973540393848585',
    messagingSenderId: '57142357984',
    projectId: 'mobile-project-b524e',
    authDomain: 'mobile-project-b524e.firebaseapp.com',
    storageBucket: 'mobile-project-b524e.appspot.com',
    measurementId: 'G-6RFE1CXTHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXjg5G0-rCYRu5ar6-JhR720vFIC442rw',
    appId: '1:57142357984:android:92bc215b9c60af0d848585',
    messagingSenderId: '57142357984',
    projectId: 'mobile-project-b524e',
    storageBucket: 'mobile-project-b524e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt4pA77gKFSvn4xuxT3s0PVqFFkTwjHKE',
    appId: '1:57142357984:ios:8fcbacdc3a1dd9c7848585',
    messagingSenderId: '57142357984',
    projectId: 'mobile-project-b524e',
    storageBucket: 'mobile-project-b524e.appspot.com',
    iosBundleId: 'com.example.mobileProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt4pA77gKFSvn4xuxT3s0PVqFFkTwjHKE',
    appId: '1:57142357984:ios:86ef7107bda249a8848585',
    messagingSenderId: '57142357984',
    projectId: 'mobile-project-b524e',
    storageBucket: 'mobile-project-b524e.appspot.com',
    iosBundleId: 'com.example.mobileProject.RunnerTests',
  );
}
